config/routes.rb
Rails.application.routes.draw do
  devise_for :chefs
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	resources :chefs do 
		resources :events
	end

	resources :events

	root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  # Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	attr_accessor :login

  devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :validatable
	has_many :events

	def self.find_for_database_authentication warden_conditions
		conditions = warden_conditions.dup
		login = conditions.delete(:login)
		where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
	end
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :chef
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	
	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation, :name, :description])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :password_confirmation])
		devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password, :name, :description])
	end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

	# only index and show routes here, the rest are handled by devise

	def index
		@chefs = Chef.all
  end

	def show
		@chef = Chef.find(params[:id])
		@events = @chef.events
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	# should this be authenticate_user or authenticate_chef?
	before_action :authenticate_chef!, :except => [ :show, :index ]
	
	def index
		if params.has_key?(:chef_id)
			@events = Event.where(chef_id: params[:chef_id] )
		else
			@events = Event.all
		end
  end

	def show
		@event = Event.find(params[:id])
  end

	def new
  end

	def edit
		@event = Event.find(params[:id])
  end
	
	def create
		@event = Event.new(event_params)
		@event.chef = current_chef
		
		@event.save
		redirect_to @event
  end
	
	def update
		@event = Event.find(params[:id])
	
		@event.update(event_params)
		redirect_to @event
  end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy

		redirect_to entries_path
	end
	
	private
  def event_params
    params.require(:event).permit(:title, :location, :date, :description, :chef_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chefs/index.html.erb
<h1>Chefs</h1>

<br><%= link_to 'Events', events_path %></p>

<% @chefs.each do |chef| %>

<p><%= chef.name %><br>
<%= chef.description %></p>

<% end %>

app/views/chefs/show.html.erb
<h1><%= @chef.name %></h1>

<p>Description: <br>
<%= @chef.description %></p>

<%= link_to 'Back', chefs_path %>

app/views/events/index.html.erb
<h1>Events Index Here</h1>

<p><%= link_to 'Chefs', chefs_path %></p>

<p>Log out if logged in and vice versa. This could be in the navbar or footer bar in views/layouts/application.html.erb<br>
<% if chef_signed_in? %>
<%= link_to 'New Event', new_event_path %><br>
<%= link_to 'Chef Log Out', destroy_chef_session_url, method: :delete %><br>
<%= link_to 'Edit Chef Profile', edit_chef_registration_url %>
<% else %>
<%= link_to 'Chef Log In', new_chef_session_url %>
<% end %>
</p>

app/views/events/new.html.erb
<h1>Incomplete</h1>

<%= form_with scope: :event, url: events_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1>Incomplete<h1>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project 3: Foodtruck</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>